### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by ulgoran** [NGSolve/ngs-special-functions#8]
Hi,
I tried to build the package following the instruction but when I run the demo bessel.py I get an Import Error

ImportError: /python3.8/site-packages/ngsolve/special_functions.so: undefined symbol: _ZNK5ngfem19CoefficientFunction14GetDescriptionB5cxx11Ev

I am using ngsolve 6.2.2301, could it be a problem with the version of ngsolve?

**Comment by ChrLackner** [comment]
Can you try using 
```
cmake -DCMAKE_CXX_FLAGS='-fabi-version=14 -D_GLIBCXX_USE_CXX11_ABI=0'
```
when configuring? This is likely because of cxx11 abi incompatibilty between how we compile ngsolve and the extension.
We are currently working on a way to fix this.

**Comment by mhochsteger** [comment]
This is fixed with the latest python packages (prerelease).
Try with an updated ngsolve:
`pip install --pre --update ngsolve`
